apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-api
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:6f2f050f3b8749e6cb46e2f3488d6366da007a144ad290c6f93a6feb28fc6071
  name: harbor.safranys.com/chatwithdocs/api
  newName: harbor.safranys.com/chatwithdocs/api
