apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-api
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:f5da43775b8b51ffef2f9d833d658962f3a3fe1fd0f4dbf8a5c7f7a3026a3f29
  name: harbor.safranys.com/chatwithdocs/api
  newName: harbor.safranys.com/chatwithdocs/api
