apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-api
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:3f3a400fd6a91ee972218b41aa5f8f1f48ba2eafce40cce9bfe0216c71321f15
  name: harbor.safranys.com/chatwithdocs/api
  newName: harbor.safranys.com/chatwithdocs/api
