# kubernetes-ansible/deploy_app_playbook.yml

- name: Install packages linux
  hosts: master # Target the master node as it has kubectl configured
  become: true # All tasks will run with sudo
  gather_facts: true
  roles:
    - helm
