apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  namespace: chatwithdocs-web
data:
  NEXT_PUBLIC_API_URL: "https://api.chatwithdocs.org"
  NEXT_PUBLIC_APP_BASE_URL: "https://chatwithdocs.org"
  # NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET: GnWwnbk0oMlnLzdCNJoBUik3pHhHBBOi
  # NEXT_PUBLIC_KEYCLOAK_URL: "https://identite.lodysaintgermain.com"
  # NEXT_PUBLIC_KEYCLOAK_REALM: "chatwithdocs"
  # NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "chatwithdocs-web"