apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-web

commonLabels:
  app.kubernetes.io/name: chatwithdocs-web
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:52c0cc8ab14225c62502e7026f58b35cdfd2eff2f9a0e10defe907aa86d4a1ec
  name: harbor.safranys.com/chatwithdocs/web
  newName: harbor.safranys.com/chatwithdocs/web
