apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-web

commonLabels:
  app.kubernetes.io/name: chatwithdocs-web
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:20beee6e32bea9853f3ac9c61416d2536e4f8db8117783cebe9ea1a7bd96755c
  name: harbor.safranys.com/chatwithdocs/web
  newName: harbor.safranys.com/chatwithdocs/web
