apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-web

commonLabels:
  app.kubernetes.io/name: chatwithdocs-web
  app.kubernetes.io/part-of: chatwithdocs

resources:
- namespace.yaml
- secretproviderclass.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- digest: sha256:49febe4bde1f591db6f1465142e15f287ec4bf2c0bb809b75ee20d7d3953ff1e
  name: harbor.safranys.com/chatwithdocs/web
  newName: harbor.safranys.com/chatwithdocs/web
