apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web-azure-keyvault-env
  namespace: chatwithdocs-web
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "graphrag-kv-web"
    tenantID: "f387bed5-f1ed-4801-9df7-837a8905a354"
    objects: |
      array:
        - |
          objectName: rag-api-url
          objectAlias: RAG_API_URL
          objectType: secret
        - |
          objectName: next-public-api-url
          objectAlias: NEXT_PUBLIC_API_URL
          objectType: secret
        - |
          objectName: next-public-app-base-url
          objectAlias: NEXT_PUBLIC_APP_BASE_URL
          objectType: secret
        - |
          objectName: next-public-default-tenant-key
          objectAlias: NEXT_PUBLIC_DEFAULT_TENANT_KEY
          objectType: secret
        - |
          objectName: next-public-auth-disabled
          objectAlias: NEXT_PUBLIC_AUTH_DISABLED
          objectType: secret
        - |
          objectName: auth-cookie-name
          objectAlias: AUTH_COOKIE_NAME
          objectType: secret
