# infra/argocd/apps/worker.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatwithdocs-worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coumarane/chatwithdocs.git
    targetRevision: dev
    path: infra/k8s/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: chatwithdocs-worker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
