apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-smoke

commonLabels:
  app.kubernetes.io/name: chatwithdocs-smoke
  app.kubernetes.io/part-of: chatwithdocs

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: harbor.safranys.com/chatwithdocs/smoke-web
    newName: harbor.safranys.com/chatwithdocs/smoke-web
    newTag: latest
