apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-worker
  app.kubernetes.io/part-of: chatwithdocs

resources:
- deployment.yaml

images:
- digest: sha256:868fb515aefd332e3d02d5f581b8d20c5175707f7e5e978330eebdf608d89cc1
  name: harbor.safranys.com/chatwithdocs/worker
  newName: harbor.safranys.com/chatwithdocs/worker
