apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-worker
  app.kubernetes.io/part-of: chatwithdocs

resources:
- deployment.yaml

images:
- digest: sha256:faf8c06e1f47794f9fb7306983c09bd468ba03317a5b969d9b1d407f05f85274
  name: harbor.safranys.com/chatwithdocs/worker
  newName: harbor.safranys.com/chatwithdocs/worker
