apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwithdocs-api

commonLabels:
  app.kubernetes.io/name: chatwithdocs-worker
  app.kubernetes.io/part-of: chatwithdocs

resources:
- deployment.yaml

images:
- digest: sha256:c615c1b331447159f6abbd39a2986bbe6abf889e985b6f7efed67161390f5a8f
  name: harbor.safranys.com/chatwithdocs/worker
  newName: harbor.safranys.com/chatwithdocs/worker
